<a href="https://colab.research.google.com/github/monasin28/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy


In [1]:
import numpy as np #np is an alias of numpy, here np is like nickname of numpy sp that we can use np instead of numpy

In [3]:
my_list=[2,3,4,6,7]

In [4]:
type(my_list)

list

Converting a list into an array we have to use function

In [5]:
arr=np.array(my_list)

In [6]:
print(arr)

[2 3 4 6 7]


In [7]:
type(arr) #n dimensional array - 1 dimensional array

numpy.ndarray

In [8]:
arr.shape

(5,)

2 Dimensional Array-multinested array-multidimensional array

In [10]:
my_list_1=[2,4,6,7,9]
my_list_2=[3,7,9,2,0]
my_list_3=[6,9,8,2,5]
arr_new=np.array([my_list_1, my_list_2, my_list_3])

In [11]:
print(arr_new) #metrics

[[2 4 6 7 9]
 [3 7 9 2 0]
 [6 9 8 2 5]]


In [12]:
arr_new.shape #3 rows & 5 column

(3, 5)

Transpose of the metrics ( Converting rows into column & column into rows)

In [14]:
arr_new.reshape(5,3) #transpose

array([[2, 4, 6],
       [7, 9, 3],
       [7, 9, 2],
       [0, 6, 9],
       [8, 2, 5]])

Q. Create a numpy matrix of shape(2,4)

In [15]:
my_list_1=[3,6,7,1]
my_list_2=[7,9,4,3]
arr_new=np.array([my_list_1, my_list_2])

In [16]:
print(arr_new)

[[3 6 7 1]
 [7 9 4 3]]


In [18]:
arr_new.reshape(4,2)

array([[3, 6],
       [7, 1],
       [7, 9],
       [4, 3]])

Numerical Analysis
(Numerical analysis on a single array)

In [19]:
a=np.array([2,3,5,6,9])
print("adding 1 to each number from the list", a+1)
print("subtract 1 to each number from the list", a-1)
print("multiply 5 to each element from the list", a*5)
print("square of each element from the list", a**2)

adding 1 to each number from the list [ 3  4  6  7 10]
subtract 1 to each number from the list [1 2 4 5 8]
multiply 5 to each element from the list [10 15 25 30 45]
square of each element from the list [ 4  9 25 36 81]


Generating Random numbers

In [25]:
np.arange(1,20,1)  #from 1 to 20 we will get equally spaced numbers(stepsize is 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [27]:
np.arange(1,20,3)  #each numbers will have an equal difference of 3

array([ 1,  4,  7, 10, 13, 16, 19])

Both arange and linspace are the functions

In [28]:
np.linspace(1,10,50)  # here 50 is the number of elements we need between 1 to 10 (here 10 is not exclusive)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [30]:
np.linspace(1,10,100)  #here 50 numbers of range 1 to 10 are divided in equal parts

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

Generating a Random float number between 0 to 1 (here 1 will be exclusive)

In [37]:
num=np.random.rand()

In [38]:
print(num)

0.4881767384129141


In [43]:
int_num=np.random.randint(0,10) #everytime when we print it will appear new random number

In [44]:
print(int_num)

4


In [46]:
np.random.rand(3,4)  #here 3 means number of rows & 4 means the number of column

array([[0.20942319, 0.40299079, 0.45535088, 0.19116278],
       [0.0640505 , 0.14297975, 0.60582369, 0.49556023],
       [0.214318  , 0.74065796, 0.98113117, 0.00592572]])